name: agentic-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - setuptools
  - wheel
  - pip:
    - aiofiles==24.1.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.11.11
    - aiosignal==1.3.2
    - aiosqlite==0.21.0
    - annotated-types==0.7.0
    - anyio==4.9.0
    - asyncio-mqtt==0.16.2
    - attrs==25.3.0
    - babel==2.17.0
    - banks==2.1.2
    - bcrypt==4.3.0
    - beautifulsoup4==4.13.4
    - black==24.10.0
    - boto3==1.38.27
    - botocore==1.38.27
    - bullmq==2.15.0
    - certifi==2025.4.26
    - cffi==1.17.1
    - cfgv==3.4.0
    - charset-normalizer==3.4.2
    - click==8.1.8
    - colorama==0.4.6
    - coverage==7.8.2
    - cryptography==45.0.3
    - dataclasses-json==0.6.7
    - Deprecated==1.2.18
    - dirtyjson==1.0.8
    - distlib==0.3.9
    - distro==1.9.0
    - ecdsa==0.19.1
    - fastapi==0.115.6
    - filelock==3.18.0
    - filetype==1.2.0
    - flake8==7.1.1
    - frozenlist==1.6.0
    - fsspec==2025.5.1
    - ftfy==6.3.1
    - ghp-import==2.1.0
    - greenlet==3.2.2
    - griffe==1.7.3
    - grpcio==1.71.0
    - grpcio-tools==1.71.0
    - h11==0.16.0
    - h2==4.2.0
    - hf-xet==1.1.2
    - hpack==4.1.0
    - httpcore==1.0.9
    - httptools==0.6.4
    - httpx==0.28.1
    - huggingface-hub==0.32.3
    - hyperframe==6.1.0
    - identify==2.6.12
    - idna==3.10
    - iniconfig==2.1.0
    - isort==5.13.2
    - Jinja2==3.1.6
    - jiter==0.10.0
    - jmespath==1.0.1
    - joblib==1.5.1
    - jsonpatch==1.33
    - jsonpointer==3.0.0
    - langchain==0.3.25
    - langchain-core==0.3.63
    - langchain-openai==0.2.12
    - langchain-text-splitters==0.3.8
    - langgraph==0.3.28
    - langgraph-checkpoint==2.0.26
    - langgraph-prebuilt==0.1.8
    - langgraph-sdk==0.1.70
    - langsmith==0.2.11
    - llama-cloud==0.1.23
    - llama-cloud-services==0.6.25
    - llama-index==0.12.39
    - llama-index-agent-openai==0.4.9
    - llama-index-cli==0.4.2
    - llama-index-core==0.12.39
    - llama-index-embeddings-openai==0.3.1
    - llama-index-indices-managed-llama-cloud==0.7.2
    - llama-index-llms-openai==0.4.0
    - llama-index-multi-modal-llms-openai==0.5.1
    - llama-index-program-openai==0.3.2
    - llama-index-question-gen-openai==0.3.1
    - llama-index-readers-file==0.4.8
    - llama-index-readers-llama-parse==0.4.0
    - llama-index-vector-stores-qdrant==0.6.0
    - llama-parse==0.6.25
    - lxml==5.4.0
    - Markdown==3.7
    - markdown-it-py==3.0.0
    - markdown2==2.5.3
    - markdownify==1.1.0
    - marker-pdf==1.7.3
    - MarkupSafe==3.0.2
    - marshmallow==3.26.1
    - mccabe==0.7.0
    - mdurl==0.1.2
    - mergedeep==1.3.4
    - mkdocs==1.6.1
    - mkdocs-get-deps==0.2.0
    - mkdocs-material==9.5.48
    - mkdocs-material-extensions==1.3.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - multidict==6.4.4
    - mypy==1.13.0
    - mypy_extensions==1.1.0
    - nest-asyncio==1.6.0
    - networkx==3.5
    - nltk==3.9.1
    - nodeenv==1.9.1
    - numpy==2.2.6
    - openai==1.82.1
    - orjson==3.10.12
    - ormsgpack==1.10.0
    - packaging==24.2
    - paginate==0.5.7
    - paho-mqtt==2.1.0
    - pandas==2.2.3
    - passlib==1.7.4
    - pathspec==0.12.1
    - pillow==11.2.1
    - platformdirs==4.3.8
    - pluggy==1.6.0
    - portalocker==2.10.1
    - pre_commit==4.0.1
    - propcache==0.3.1
    - protobuf==5.29.5
    - pyasn1==0.6.1
    - pycodestyle==2.12.1
    - pycparser==2.22
    - pydantic==2.10.4
    - pydantic-settings==2.7.0
    - pydantic_core==2.27.2
    - pyflakes==3.2.0
    - Pygments==2.19.1
    - PyJWT==2.8.0
    - pymdown-extensions==10.15
    - pypdf==5.5.0
    - PyPDF2==3.0.1
    - pytest==8.3.4
    - pytest-asyncio==0.24.0
    - pytest-cov==6.0.0
    - pytest-mock==3.14.0
    - python-dateutil==2.9.0.post0
    - python-docx==1.1.2
    - python-dotenv==1.0.1
    - python-jose==3.3.0
    - python-magic-bin==0.4.14
    - python-multipart==0.0.20
    - pytz==2025.2
    - PyYAML==6.0.2
    - pyyaml_env_tag==1.1
    - qdrant-client==1.12.1
    - RapidFuzz==3.13.0
    - redis==5.2.1
    - regex==2024.11.6
    - requests==2.32.3
    - requests-toolbelt==1.0.0
    - rich==13.9.4
    - rsa==4.9.1
    - s3transfer==0.13.0
    - safetensors==0.5.3
    - scikit-learn==1.6.1
    - scipy==1.15.3
    - semver==2.13.0
    - six==1.17.0
    - sniffio==1.3.1
    - soupsieve==2.7
    - SQLAlchemy==2.0.41
    - starlette==0.41.3
    - striprtf==0.0.26
    - structlog==24.4.0
    - sympy==1.13.3
    - tenacity==9.1.2
    - threadpoolctl==3.6.0
    - tiktoken==0.9.0
    - tokenizers==0.21.1
    - torch==2.2.2
    - torchaudio==2.2.2
    - torchvision==0.17.2
    - tqdm==4.67.1
    - transformers==4.52.4
    - typesense==0.21.0
    - typing-inspect==0.9.0
    - typing_extensions==4.12.2
    - tzdata==2025.2
    - urllib3==2.4.0
    - uvicorn==0.32.1
    - uvloop==0.21.0
    - virtualenv==20.31.2
    - watchdog==6.0.0
    - watchfiles==1.0.5
    - wcwidth==0.2.13
    - websockets==15.0.1
    - wrapt==1.17.2
    - xxhash==3.5.0
    - yarl==1.20.0 