name: agentic-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=1.26.4
  - pillow=10.4.0
  - pip
  - pip:
    # Core framework
    - fastapi==0.115.6
    - uvicorn[standard]==0.32.1
    - pydantic==2.10.4
    - pydantic-settings==2.7.0
    
    # Redis and job queue
    - redis==5.2.1
    - bullmq==2.15.0
    
    # HTTP clients
    - httpx==0.28.1
    - aiohttp==3.11.11
    
    # Configuration and logging
    - python-dotenv==1.0.1
    - structlog==24.5.0
    - rich==13.9.4
    
    # Date and JSON handling
    - python-dateutil==2.9.0.post0
    - orjson==3.10.12
    
    # Type hints
    - typing-extensions==4.12.2
    
    # CRITICAL: Install torch/torchvision with specific index for compatibility
    # Use CPU version for maximum compatibility
    - --index-url https://download.pytorch.org/whl/cpu
    - torch==2.7.0
    - torchvision==0.22.0
    - --index-url https://pypi.org/simple/
    
    # Document processing (Marker)
    - marker-pdf==1.7.3
    - tabulate
    
    # Document processing fallback libraries
    - python-docx==1.1.2
    - python-pptx==1.0.2
    - html2text==2024.2.26
    - ebooklib==0.18
    - beautifulsoup4==4.12.3
    
    # Vector database and search
    - qdrant-client==1.12.1
    - typesense==0.21.0
    
    # Async utilities
    - asyncio-mqtt==0.16.2
    
    # Testing
    - pytest==8.3.4
    - pytest-asyncio==0.25.0
    - pytest-cov==6.0.0
    - pytest-mock==3.14.0
    
    # Development tools
    - black==24.10.0
    - isort==5.13.2
    - flake8==7.1.1
    - mypy==1.13.0
    - pre-commit==4.0.1
    
    # Documentation
    - mkdocs==1.6.1
    - mkdocs-material==9.5.48
    
    # Security
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - PyJWT==2.8.0
    
    # Utilities
    - click==8.1.8
    - tqdm==4.67.1
    
    # File handling
    - python-multipart==0.0.20
    - boto3==1.35.95
    - botocore==1.35.95
    - aiofiles==24.1.0
    
    # LangGraph and AI
    - langgraph==0.3.28
    - langgraph-api==0.1.9
    - langchain-openai==0.2.12
    - langchain-core==0.3.30
    - langchain-community==0.3.30
    - openai==1.57.2
    
    # LlamaIndex
    - llama-index==0.12.9
    - llama-index-vector-stores-qdrant==0.4.1
    - llama-index-embeddings-openai==0.3.2
    - llama-index-llms-openai==0.3.6
    
    # Document utilities
    - python-magic==0.4.27
    - markdown==3.7
    - instructor==1.10.1
    
    # Data processing
    - pandas>=2.0.0
    - PyPDF2>=3.0.0
    
    # Visualization
    - matplotlib>=3.7.0
    - plotly>=5.17.0
    
    # WebSocket support
    - websockets>=12.0 